# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vlazuka <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/07 15:17:16 by vlazuka           #+#    #+#              #
#    Updated: 2018/08/07 15:45:03 by vlazuka          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=do-op
SRCS=files/do_op.c files/ft_atoi.c files/ft_add.c files/ft_div.c files/ft_mod.c files/ft_mul.c files/ft_sub.c

all:
	gcc $(SRCS) -o $(NAME)

clean:
	/bin/rm -f $(NAME)

re: clean all
