#!/bin/sh
#echo "42 school is a Charm!"

print_date()
{
echo "Today is `date +"%A %d %B %Y (%r)"`"
return
}
print_date

#printf -- 'doing something... \n';
#printf -- '\033[37m someone else's output \033[0m\n';
#printf -- '\033[32m SUCCESS: yay \033[0m\n';
#printf -- '\033[33m WARNING: hmm \033[0m\n';
#printf -- '\033[31m ERROR: fubar \033[0m\n';
